import { basicTheme } from "theme";
import { SxStyles } from "types/styles";

export const styles: SxStyles = {
  root: {
    display: { mobile: "none", tablet: "flex" },
    flexDirection: "column",
    justifyContent: "space-between",
    flex: 1,
    bgcolor: basicTheme.palette.mainPalette.primary,
    borderRadius: 6,
    p: 8,
    m: 4,
    overflow: "hidden",
    position: "relative",
  },
  tilesRow: {
    display: "flex",
    gap: 4,
    flex: 1,
    alignItems: "flex-start",
  },
  tile: {
    flex: 1,
    borderRadius: 5,
    background: `linear-gradient(135deg, ${basicTheme.palette.mainPalette.primaryLight}55 0%, ${basicTheme.palette.mainPalette.primary}aa 100%)`,
    border: `1px solid ${basicTheme.palette.mainPalette.primaryLight}44`,
    position: "relative",
    aspectRatio: "3/4",
  },
  tileLeft: {
    display: "flex",
    alignItems: "flex-end",
    p: 3,
  },
  participantBadge: {
    display: "flex",
    alignItems: "center",
    gap: 1.5,
    bgcolor: "rgba(0,0,0,0.45)",
    borderRadius: 5,
    px: 3,
    py: 1,
  },
  activeDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    bgcolor: basicTheme.palette.systemPalette.red,
    flexShrink: 0,
  },
  notificationCard: {
    position: "absolute",
    right: -16,
    top: "35%",
    bgcolor: basicTheme.palette.mainPalette.white,
    borderRadius: 4,
    p: 4,
    maxWidth: 220,
    boxShadow: "0 8px 32px rgba(0,0,0,0.18)",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  notificationHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 3,
  },
  notificationAvatar: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    bgcolor: "#C8D9B0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  tagline: {
    mt: 4,
  },
};
