import { basicTheme } from "theme";
import { SxStyles } from "types/styles";

const { mainPalette, accentPalette } = basicTheme.palette;

export const styles: SxStyles = {
  root: {
    flex: 1,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    padding: { mobile: "0 0 32px", tablet: "0 24px 40px" },
    width: "100%",
  },
  heroBanner: {
    borderRadius: { mobile: "0 0 16px 16px", tablet: "16px" },
    backgroundColor: mainPalette.primary,
    padding: { mobile: "20px 20px 24px", tablet: "28px 32px 32px" },
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    flexShrink: 0,
  },
  breadcrumb: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "rgba(255,255,255,0.6)",
    fontSize: "13px",
    fontFamily: "'Proba Pro', Arial, serif",
  },
  breadcrumbSep: {
    color: "rgba(255,255,255,0.4)",
    fontSize: "13px",
  },
  breadcrumbCurrent: {
    color: "rgba(255,255,255,0.9)",
    fontSize: "13px",
    fontFamily: "'Proba Pro', Arial, serif",
  },
  heroTitle: {
    color: mainPalette.white,
    fontFamily: "'RockStarBold', Arial, serif",
    fontSize: "36px !important",
    fontWeight: "700 !important",
    lineHeight: "1.1 !important",
  },
  card: {
    backgroundColor: mainPalette.white,
    borderRadius: "16px",
    padding: { mobile: "20px 16px", tablet: "24px 28px" },
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    mx: { mobile: "12px", tablet: 0 },
  },
  profileCardRow: {
    display: "flex",
    flexDirection: { mobile: "column", tablet: "row" },
    alignItems: { mobile: "flex-start", tablet: "center" },
    gap: "20px",
  },
  avatarWrap: {
    position: "relative",
    flexShrink: 0,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: "50%",
    background: `radial-gradient(circle at 35% 35%, ${mainPalette.primaryLight}, ${mainPalette.primary})`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitials: {
    color: mainPalette.white,
    fontFamily: "'RockStarBold', Arial, serif",
    fontSize: "24px !important",
    fontWeight: "700 !important",
  },
  avatarEditBtn: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 26,
    height: 26,
    borderRadius: "50%",
    backgroundColor: mainPalette.white,
    border: "1.5px solid rgba(0,0,0,0.1)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    "&:hover": { backgroundColor: "rgba(0,0,0,0.04)" },
  },
  profileInfo: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  profileName: {
    fontFamily: "'RockStarBold', Arial, serif",
    fontSize: "20px !important",
    fontWeight: "700 !important",
    color: accentPalette.text,
  },
  profileMeta: {
    fontSize: "13px !important",
    color: accentPalette.text,
    opacity: 0.6,
  },
  profileMetaBold: {
    fontWeight: "600 !important",
    opacity: 1,
    color: accentPalette.text,
  },
  badges: {
    display: "flex",
    gap: "6px",
    mt: "4px",
  },
  badge: {
    fontSize: "12px",
    fontFamily: "'Proba Pro', Arial, serif",
    color: accentPalette.text,
    backgroundColor: "rgba(84,107,65,0.1)",
    borderRadius: "20px",
    px: "10px",
    py: "3px",
  },
  viewCardBtn: {
    ml: { mobile: 0, tablet: "auto" },
    padding: "10px 20px",
    borderRadius: "12px",
    backgroundColor: "rgba(84,107,65,0.1)",
    border: "none",
    cursor: "pointer",
    fontFamily: "'RockStarMedium', Arial, serif",
    fontWeight: "500",
    fontSize: "14px",
    color: accentPalette.text,
    "&:hover": { backgroundColor: "rgba(84,107,65,0.17)" },
  },
  cardTitle: {
    fontSize: "15px !important",
    fontWeight: "600 !important",
    fontFamily: "'RockStarBold', Arial, serif",
    color: accentPalette.text,
  },
  fieldLabel: {
    fontSize: "12px !important",
    color: accentPalette.text,
    opacity: 0.55,
    mb: "6px",
  },
  fieldInput: {
    borderRadius: "12px",
    border: "1.5px solid rgba(0,0,0,0.09)",
    padding: "12px 14px",
    backgroundColor: mainPalette.white,
    fontSize: "14px",
    fontFamily: "'Proba Pro', Arial, serif",
    color: accentPalette.text,
  },
  fieldsGrid: {
    display: "grid",
    gridTemplateColumns: { mobile: "1fr", tablet: "1fr 1fr" },
    gap: "14px",
  },
  bioHint: {
    fontSize: "12px !important",
    color: accentPalette.text,
    opacity: 0.5,
    mb: "6px",
  },
  bioInput: {
    borderRadius: "12px",
    border: "1.5px solid rgba(0,0,0,0.09)",
    padding: "12px 14px",
    backgroundColor: mainPalette.white,
    minHeight: 96,
    fontSize: "14px",
    fontFamily: "'Proba Pro', Arial, serif",
    color: accentPalette.text,
    resize: "vertical" as const,
    width: "100%",
    boxSizing: "border-box" as const,
    outline: "none",
    "&:focus": { borderColor: mainPalette.primary },
  },
  whenJoinTitle: {
    fontSize: "15px !important",
    fontWeight: "600 !important",
    fontFamily: "'RockStarBold', Arial, serif",
    color: accentPalette.text,
  },
  whenJoinSubtitle: {
    fontSize: "13px !important",
    color: accentPalette.text,
    opacity: 0.55,
  },
  saveBtn: {
    alignSelf: "flex-end",
    padding: "10px 24px",
    borderRadius: "12px",
    backgroundColor: mainPalette.primary,
    border: "none",
    cursor: "pointer",
    fontFamily: "'RockStarMedium', Arial, serif",
    fontWeight: "500",
    fontSize: "14px",
    color: mainPalette.white,
    "&:hover": { opacity: 0.88 },
  },
  deleteBtn: {
    alignSelf: "flex-start",
    padding: "10px 24px",
    borderRadius: "12px",
    backgroundColor: "rgba(200,50,50,0.08)",
    border: "none",
    cursor: "pointer",
    fontFamily: "'RockStarMedium', Arial, serif",
    fontWeight: "500",
    fontSize: "14px",
    color: "#c83232",
    "&:hover": { backgroundColor: "rgba(200,50,50,0.15)" },
  },
  debugBtn: {
    alignSelf: "flex-start",
    padding: "8px 20px",
    borderRadius: "12px",
    backgroundColor: "rgba(0,0,0,0.05)",
    border: "1.5px dashed rgba(0,0,0,0.15)",
    cursor: "pointer",
    fontFamily: "'Proba Pro', Arial, serif",
    fontSize: "13px",
    color: accentPalette.text,
    opacity: 0.7,
    "&:hover": { opacity: 1 },
  },
};
