import { basicTheme } from "theme";

const { mainPalette } = basicTheme.palette;

export const styles = {
  root: {
    position: "relative",
    borderRadius: "16px",
    overflow: "hidden",
    width: "100%",
    height: "100%",
    minHeight: 0,
    background: `radial-gradient(circle at 35% 35%, ${mainPalette.primaryLight}, ${mainPalette.primary})`,
  },
  cameraOff: {
    backgroundColor: "#2e3d25",
    background: "#2e3d25",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  initialsAvatar: {
    width: 64,
    height: 64,
    borderRadius: "50%",
    backgroundColor: "rgba(255,255,255,0.15)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: mainPalette.white,
    fontFamily: "'RockStarBold', Arial, serif",
    fontSize: "22px",
    fontWeight: 700,
  },
  speakingBadge: {
    position: "absolute",
    top: 10,
    left: 10,
    display: "flex",
    alignItems: "center",
    gap: "5px",
    backgroundColor: "rgba(40,55,30,0.75)",
    borderRadius: "20px",
    px: "10px",
    py: "4px",
  },
  speakingDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    backgroundColor: "#7ed85b",
  },
  speakingText: {
    color: mainPalette.white,
    fontSize: "11px",
    fontFamily: "'Proba Pro', Arial, serif",
  },
  roleBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "rgba(40,55,30,0.75)",
    borderRadius: "20px",
    px: "10px",
    py: "4px",
    color: mainPalette.white,
    fontSize: "11px",
    fontFamily: "'Proba Pro', Arial, serif",
  },
  nameBadge: {
    position: "absolute",
    bottom: 10,
    left: 10,
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "rgba(40,55,30,0.75)",
    borderRadius: "20px",
    px: "10px",
    py: "4px",
    color: mainPalette.white,
    fontSize: "12px",
    fontFamily: "'Proba Pro', Arial, serif",
  },
  mutedIconWrap: {
    position: "absolute",
    bottom: 10,
    right: 10,
    width: 28,
    height: 28,
    borderRadius: "50%",
    backgroundColor: "rgba(40,55,30,0.75)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
};
